<a href="https://colab.research.google.com/github/dhoneshruti59-cloud/task23/blob/main/task23_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded=files.upload()

Saving student performance dataset.csv to student performance dataset.csv

In [3]:
filepath="/content/student performance dataset.csv"
df=pd.read_csv("student performance dataset.csv")

In [4]:
df.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   object
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          898 non-null    object
 6   internet_access             1000 non-null   object
 7   extracurricular_activities  1000 non-null   object
 8   part_time_job               1000 non-null   object
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [6]:
df.isnull().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [7]:
df=df.dropna()

In [8]:
df=df.drop_duplicates()

In [18]:
X = df.drop("final_exam_score", axis=1)
y = df["final_exam_score"]

print("Shape of X:",X.shape)
print("Shape of y:",y.shape)

Shape of X: (898, 11)
Shape of y: (898,)

In [19]:
X=pd.get_dummies(X,drop_first=True)
X=X.astype(int)

In [20]:
from sklearn.preprocessing import StandardScaler
num_cols = [
    "study_time_hours",
    "attendance_percent",
    "sleep_hours",
    "final_exam_score"
]
num_cols = [col for col in num_cols if col in X.columns]
scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [22]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [25]:
y_pred = model.predict(X_test)
print("prediction:",y_pred)

prediction: [75.83812773 75.71256473 96.10228763 97.19344045 68.02882619 94.64970659
 95.48837529 67.05369531 95.51056114 85.50062143 72.79978259 65.21786229
 85.53174464 86.34406946 85.82338329 84.35035229 94.47953045 85.53789006
 78.14504063 84.83427689 74.58646867 75.21748902 75.53435902 97.74390433
 56.4951377  97.93289351 85.47165269 77.18457023 95.34860215 95.09853597
 66.2274816  64.89092077 85.94297672 89.18367533 84.65119394 94.62425112
 97.19298786 85.04596251 75.90216353 93.897948   83.7351699  97.18538103
 74.58867576 98.37578746 83.62060435 74.37728579 75.93023287 75.67953775
 86.20140852 96.01664623 75.24192759 96.09325076 84.31887788 76.46106363
 85.66480652 74.73123044 85.94841066 95.23400101 97.54482493 73.69374429
 85.58585687 84.71420922 84.58852496 66.35533521 95.87673896 95.7938528
 79.16207995 84.3910265  74.17967856 94.03933812 95.46351516 93.50559139
 85.88570051 83.99899443 97.12790986 86.16145131 83.67600933 84.23940935
 96.74419009 95.66554489 95.66086229 65.1265294  87.20509315 85.46904466
 77.18626881 83.9312686  99.02703604 76.91901936 85.455276   85.74636001
 87.06895129 84.18836762 75.90471958 74.19181523 65.47197531 74.19847768
 74.92850482 75.4793329  95.82377324 67.06716857 75.31726387 92.37233362
 96.09780767 83.35328109 84.52951742 77.63882549 95.05232942 95.4010643
 83.28059691 94.78867227 84.22941089 97.27046692 86.20905391 86.4089608
 96.42473903 75.08544892 76.05252199 84.95429143 64.98649793 76.33834935
 73.57583209 85.2742258  98.67282806 97.70567977 94.93117163 85.28728314
 66.1107549  86.28216136 73.8655668  99.22373539 77.0669435  97.32173231
 86.64285869 66.04865551 93.97469476 74.3161651  85.0901254  96.31442385
 76.16614937 83.64276086 95.48510084 85.07716672 96.01808563 75.88390407
 97.5183877  85.32174046 85.37302704 76.80797    84.49228926 95.50930211
 84.2308576  86.17899259 67.08331075 75.08378344 75.5546846  75.21890753
 94.63552531 86.72192756 96.93454191 84.47236777 74.98815323 95.24996797
 65.22520231 93.78223728 66.09938546 85.70354373 96.55413728 58.22201562
 74.32198144 96.50958676 97.19754809 98.08947366 85.72812373 84.3443288
 83.37257235 74.40984463 86.32375422 86.85549623 83.57416295 82.86242947]

In [26]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

R2 Score: 0.9335403333060819

In [27]:
prediction_df = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

prediction_df.head(10)

   Actual  Predicted
0    75.4  75.838128
1    72.1  75.712565
2    93.6  96.102288
3    96.4  97.193440
4    68.0  68.028826
5    95.1  94.649707
6    93.5  95.488375
7    67.8  67.053695
8    98.3  95.510561
9    84.7  85.500621